package com.home.piperbike.auth

object Rights {
    const val CAN_READ_USER_ACTIVITIES = "CAN_READ_USER_ACTIVITIES"
    const val CAN_CREATE_USER_ACTIVITY = "CAN_CREATE_USER_ACTIVITY"
    const val CAN_EDIT_USER_ACTIVITY = "CAN_EDIT_USER_ACTIVITY"
    const val CAN_DELETE_USER_ACTIVITY = "CAN_DELETE_USER_ACTIVITY"

    const val CAN_READ_CLUB_USERS = "CAN_READ_CLUB_USERS"
    const val CAN_CREATE_CLUB_POSTS = "CAN_CREATE_CLUB_POSTS"
}