postgres:
  image: postgres:9.6.8
  container_name: piperbike_postgres
  ports:
    - "4005:5432"
  volumes:
    - postgres_data:/var/lib/postgresql
  environment:
    - POSTGRES_USER=piperbike
    - POSTGRES_PASSWORD=piperbike
    - POSTGRES_DB=piperbike
  restart: always